name: JMeter Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Calculate version
      id: calculate_version
      run: |
        if [ "${{ steps.get_version.outputs.VERSION }}" == "master" ]; then 
          NEWVERSION="latest"
        else
          NEWVERSION=${{ steps.get_version.outputs.VERSION }}
        fi
        echo ::set-output name=VERSION::$(echo ${NEWVERSION})
    - name: Show version
      id: show_version
      run: version echo ${{ steps.calculate_version.outputs.VERSION }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: intershophub/jmeter:${{ steps.calculate_version.outputs.VERSION }}
        target: nongui
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: intershophub/jmeter:${{ steps.calculate_version.outputs.VERSION }}-gui
        target: gui
    
